server:
  port: 8090

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: demouser
    password: "${password_demouser}"
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true